name: Deploy Discord Bot

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Bun
      run: |
        curl -fsSL https://bun.sh/install | bash
        echo "$HOME/.bun/bin" >> $GITHUB_PATH

    - name: Verify Bun Installation
      run: |
        source $HOME/.bashrc  # Ensure .bashrc is sourced to include Bun in the PATH
        bun --version

    - name: Install Dependencies
      run: |
        source $HOME/.bashrc  # Ensure .bashrc is sourced to include Bun in the PATH
        bun install

    - name: Start Bot
      run: |
        source $HOME/.bashrc  # Ensure .bashrc is sourced to include Bun in the PATH
        bun run start
      env:
        DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
        LLM_API: ${{ secrets.LLM_API }}
        DATABASE: ${{ secrets.DATABASE }}
        MONGO: ${{ secrets.MONGO }}

    - name: Debug Environment
      run: |
        echo "Checking PATH..."
        echo "$PATH"
        echo "Current directory..."
        pwd
        echo "List files..."
        ls -la
